[JENKINS-60926] Update to 4.2 version of Remoting.
jenkinsci/slave-installer-module pull request #7
Opened 2020-02-06 22:20 UTC by jeffret-b

See [JENKINS-60926](https://issues.jenkins-ci.org/browse/JENKINS-60926).

This corrects a minor regression introduced in Remoting 4.0 and Jenkins 2.217 (2020-01-23). A renaming broke agent Windows service installation. This restores the behavior.

Related to and needs to be connected with jenkinsci/jenkins#4476. We probably need to publish an incremental here first.

2020-02-06 22:24 UTC, jeffret-b commented
Looks like the build isn't picking up the correct incremental version of Jenkins. Maybe related to my companion PR to add incrementals here: #6.

2020-02-06 23:41 UTC, oleg-nenashev requested changes
OK, now I see the problem here. I forgot that there was no Getter added in https://github.com/jenkinsci/remoting/pull/353 , and hence such approach is likely to cause chicken-and-egg problems between this module and remoting. Maven and module loading will be likely a mess if we submit an update with incrementals version. 

Since 4.2 was released before I got to review it, now we may have to either cut 4.3 with temporary API update. And this is bad. I suggest just using reflection to pick a method or a field depending on the core version

2020-02-07 00:04 UTC, jeffret-b commented
I'll go the incrementals approach tomorrow.

2020-02-07 15:51 UTC, jeffret-b commented
Trying out a reflection-based approach. I'm still testing it out but I wanted to get the CI going to see its results.

2020-02-07 18:09 UTC, jeffret-b commented
I tested it out. It worked good in both the before (Remoting version < 4.0) and after (Remoting version >= 4.2) configurations. Please review and then we should be ready to release this and incorporate it into the Remoting 4.2 PR in core.

2020-02-07 19:11 UTC, jvz approved these changes

2020-02-07 19:11 UTC, jvz commented on src/main/java/org/jenkinsci/modules/slave_installer/impl/InstallerGui.java
> +        } catch (NoSuchMethodException | IllegalAccessException | InvocationTargetException e) {
```suggestion
        } catch (NoSuchMethodException | IllegalAccessException | InvocationTargetException ignored) {
```

2020-02-07 19:11 UTC, jvz commented on src/main/java/org/jenkinsci/modules/slave_installer/impl/InstallerGui.java
> +        } catch (NoSuchFieldException | IllegalAccessException e) {
```suggestion
        } catch (NoSuchFieldException | IllegalAccessException ignored) {
```

2020-02-07 21:13 UTC, oleg-nenashev approved these changes
Thanks @jeffret-b ! Thus code will basically stay around for 1-2 weekly releases. Will find a place in the airport to release it

2020-02-07 21:14 UTC, merged